GestionEvenementASP/Models/ErrorViewModel.cs
namespace GestionEvenementASP.Models
{
   public class ErrorViewModel
   {
      public string? RequestId { get; set; }

      public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
   }
}

GestionEvenementASP/Models/EventDate.cs
namespace GestionEvenementASP.Models
{
   public class EventDate
   {
      public DateTime StartDate { get; set; }
      public DateTime EndDate { get; set; }
   }
}

GestionEvenementASP/Models/Forms/UserLoginForm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GestionEvenementASP.Models.Forms
{
   public class UserLoginForm
   {
      [Required]
      [EmailAddress]
      public string Email { get; set; }
      [Required]
      [DataType(DataType.Password)]
      public string Password { get; set; }
   }
}

GestionEvenementASP/Models/Forms/UserRegisterForm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GestionEvenementASP.Models.Forms
{
   public class UserRegisterForm
   {
      [Required]
      [EmailAddress]
      public string Email { get; set; }
      [Required]
      [RegularExpression("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$")]
      [DataType(DataType.Password)]
      public string Password { get; set; }
      [Compare(nameof(Password), ErrorMessage = "Les Mots de passe ne sont pas identiques")]
      [DataType(DataType.Password)]
      public string PasswordConfirmation { get; set; }
      [Required]
      public string LastName { get; set; }
      [Required]
      public string FirstName { get; set; }
   }
}

GestionEvenementASP/Controllers/EventController.cs
using DAL.Interfaces;
using DAL.Models;
using DAL.Services;
using GestionEvenementASP.Models.Forms;
using GestionEvenementASP.Tools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System.Diagnostics;

namespace GestionEvenementASP.Controllers
{
   public class EventController : Controller
   {
      private readonly IEventService _eventService;
      private readonly SessionManager _sessionManager;
      public EventController(IEventService eventService, SessionManager sessionManager)
      {
         _eventService = eventService;
         _sessionManager = sessionManager;
      }
      public IActionResult List()
      {
         return View(_eventService.GetEvents());
      }

      [AdminRequired]
      public IActionResult Create()
      {
         if (TempData["event"] is null)
         {
            return View();
         }
         Event e = JsonConvert.DeserializeObject<Event>((string)TempData["event"]);
         return View(e);
      }

      [HttpPost]
      public IActionResult CreateEvent(Event e)
      {
         if (!ModelState.IsValid)
         {
            TempData["error"] = ModelState["EndDate"].Errors.First().ErrorMessage;
            string json = JsonConvert.SerializeObject(e);
            TempData["event"] = json;
            return RedirectToAction("create");
         }
         int nbrDays = (e.EndDate - e.StartDate).Days + 1;
         e.TypeByDays = new List<EventTypeDay>();
         for (int i = 0; i < nbrDays; i++)
         {
            e.TypeByDays.Add(new EventTypeDay { Date = (e.StartDate.AddDays(i)) });
         }
         return View(e);
      }
      [HttpPost]
      public IActionResult AddType(Event e)
      {

         _eventService.Create(e.ToCreate(), _sessionManager.Token);
         Event lastEvent = _eventService.GetEvents().OrderBy(x => x.Id).Last();
         int i = 0;
         foreach (EventTypeDay day in e.TypeByDays)
         {
            day.EventId = lastEvent.Id;
            day.Date = lastEvent.StartDate.AddDays(i);
            _eventService.AddTypeByDays(day.ToCreate());
            i++;
         }

         return RedirectToAction("List");
      }
   }
}

GestionEvenementASP/Controllers/HomeController.cs
using GestionEvenementASP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestionEvenementASP.Controllers
{
   public class HomeController : Controller
   {
      private readonly ILogger<HomeController> _logger;

      public HomeController(ILogger<HomeController> logger)
      {
         _logger = logger;
      }

      public IActionResult Index()
      {
         return View();
      }

      public IActionResult Privacy()
      {
         return View();
      }

      [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
      public IActionResult Error()
      {
         return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
      }
   }
}

GestionEvenementASP/Controllers/UserController.cs
using DAL.Interfaces;
using DAL.Models;
using GestionEvenementASP.Models.Forms;
using GestionEvenementASP.Tools;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace GestionEvenementASP.Controllers
{
   public class UserController : Controller
   {
      private readonly IUserService _userService;
      private readonly SessionManager _session;

      public UserController(IUserService userService, SessionManager session)
      {
         _userService = userService;
         _session = session;
      }

      public IActionResult Profil()
      {
         return View(_userService.GetById(_session.ConnectedUser.Id));
      }
      [HttpPost]
      public IActionResult UpdateUser(User user)
      {
         _userService.Update(user, _session.Token);
         return RedirectToAction("Profil");
      }
      public IActionResult Register()
      {
         return View();
      }

      [HttpPost]
      public IActionResult Register(UserRegisterForm u)
      {
         if (!ModelState.IsValid)
         {
            return View(u);
         }

         if (_userService.Register(u.Email, u.Password, u.LastName, u.FirstName))
         {
            return RedirectToAction("Index", "Game");
         }

         return View();

      }

      public IActionResult Login()
      {
         return View();
      }

      [HttpPost]
      public IActionResult Login(UserLoginForm u)
      {
         try
         {
            string token = _userService.Login(u.Email, u.Password);
            JwtSecurityToken jwt = new JwtSecurityToken(token);
            int id = int.Parse(jwt.Claims.First(x => x.Type == ClaimTypes.Sid).Value);
            User connectedUser = _userService.GetById(id);
            _session.Token = token;
            _session.ConnectedUser = connectedUser;
            return RedirectToAction("Index", "Home");

         }
         catch (Exception ex)
         {
            ViewBag.Error = ex.Message;
            return View();
         }
      }

      public IActionResult Logout()
      {
         _session.Logout();
         return RedirectToAction("Index", "Game");
      }

      public IActionResult GetById(int id)
      {
         return Ok(_userService.GetById(id));
      }

      [AdminRequired]
      public IActionResult AllUser()
      {
         return View(_userService.GetUsers(_session.Token));
      }

      [AdminRequired]
      public IActionResult SetRole(int id)
      {
         if (_userService.SetRole(id, 3, _session.Token))
         {
            return RedirectToAction("AllUser");
         }
         else
         {
            return View();
         }
      }
   }
}

GestionEvenementASP/Views/Event/AddType.cshtml
@using DAL.Interfaces;
@model DAL.Models.Event
@inject IEventService eventService

@{
   ViewData["Title"] = "CreateEvent";
}

<h1>CreateEvent</h1>

<h4>Event</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="AddType">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" type="hidden" />
            <span asp-validation-for="Name" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="StartDate" class="control-label"></label>
            <input asp-for="StartDate" class="form-control" type="hidden" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="EndDate" class="control-label"></label>
            <input asp-for="EndDate" class="form-control" type="hidden" />
            <span asp-validation-for="EndDate" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Location" class="control-label"></label>
            <input asp-for="Location" class="form-control" type="hidden" />
            <span asp-validation-for="Location" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Adress" class="control-label"></label>
            <input asp-for="Adress" class="form-control" type="hidden" />
            <span asp-validation-for="Adress" class="text-danger"></span>
         </div>
         @{
            int i = (int)TempData["i"];
            <div class="form-group">
               <label asp-for="TypeByDays.ElementAt(i)" class="control-label"></label>
               <select asp-for="TypeByDays.ElementAt(i).Type.Id" class="form-select" aria-label="Choisir Genre">
                  @foreach (var item in eventService.GetTypes())
                  {
                     <option value="@item.Id">@item.Name</option>
                  }
               </select>
               <span asp-validation-for="TypeByDays.ElementAt(i).Type.Id" class="text-danger"></span>
            </div>
            i++;
            TempData["i"] = i;
         }
         <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

GestionEvenementASP/Views/Event/AddTypeGet.cshtml
@using DAL.Interfaces;
@using DAL.Models;
@model DAL.Models.Event
@inject IEventService eventService

@{
   ViewData["Title"] = "AddType";
}

<h1>AddType</h1>

<h4>Event</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="AddType">
         @{
            int i = 0;
            foreach (var et in Model.TypeByDays)
            {
               et.Date = Model.StartDate.AddDays(i);
               <p>Jour@(i+1) @et.Date.ToString("D") :  </p>
               <div class="form-group">
                  <label asp-for="@et.Type" class="control-label"></label>
                  <select asp-for="@et.Type.Id" class="form-select" aria-label="Choisir Genre">
                     @foreach (var item in eventService.GetTypes())
                     {
                        <option value="@item.Id">@item.Name</option>
                     }
                  </select>
                  <span asp-validation-for="@et.Type.Id" class="text-danger"></span>
               </div>
               i++;
               <br />
            }
         }
         <div class="form-group">
            <input type="submit" value="Envoyer" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
   }

GestionEvenementASP/Views/Event/Create.cshtml
@model DAL.Models.Event

@{
   ViewData["Title"] = "Create";
}

<h1>Ajout d'un évenement'</h1>

<h4 class="text-danger">@TempData["error"]</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="CreateEvent">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="StartDate" class="control-label"></label>
            <input asp-for="StartDate" class="form-control" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="EndDate" class="control-label"></label>
            <input asp-for="EndDate" class="form-control" />
            <span asp-validation-for="EndDate" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="Location" class="control-label"></label>
            <input asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Adress" class="control-label"></label>
            <input asp-for="Adress" class="form-control" />
            <span asp-validation-for="Adress" class="text-danger"></span>
         </div>
         <div class="form-group">
            <input type="submit" value="Next" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

GestionEvenementASP/Views/Event/CreateEvent.cshtml
@using DAL.Interfaces;
@model DAL.Models.Event
@inject IEventService eventService

@{
   ViewData["Title"] = "CreateEvent";
}

<h1>CreateEvent</h1>

<h4>Event</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="AddType">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group" id="hidden">
            <label asp-for="Name" class="control-label" ></label>
            <input asp-for="Name" class="form-control" type="hidden" />
            <span asp-validation-for="Name" class="text-danger"></span>
         </div>
         <div class="form-group" id="hidden">
            <label asp-for="StartDate" class="control-label" ></label>
            <input asp-for="StartDate" class="form-control" type="hidden" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
         </div>
         <div class="form-group" id="hidden">
            <label asp-for="EndDate" class="control-label" ></label>
            <input asp-for="EndDate" class="form-control" type="hidden" />
            <span asp-validation-for="EndDate" class="text-danger"></span>
         </div>
         <div class="form-group" id="hidden">
            <label asp-for="Location" class="control-label" ></label>
            <input asp-for="Location" class="form-control" type="hidden" />
            <span asp-validation-for="Location" class="text-danger"></span>
         </div>
         <div class="form-group" id="hidden">
            <label asp-for="Adress" class="control-label" ></label>
            <input asp-for="Adress" class="form-control" type="hidden" />
            <span asp-validation-for="Adress" class="text-danger"></span>
         </div>
         @{
            for (int i = 0; i < Model.TypeByDays.Count(); i++)
            {
               <div class="form-group">
                  <label asp-for="TypeByDays[i]" class="control-label">@Model.TypeByDays[i].Date</label>
                  <select asp-for="TypeByDays[i].Type.Id" class="form-select" aria-label="Choisir Genre">
                     @foreach (var item in eventService.GetTypes())
                     {
                        <option value="@item.Id">@item.Name</option>
                     }
                  </select>
                  <span asp-validation-for="TypeByDays[i].Type.Id" class="text-danger"></span>
               </div>
            }
         }
         <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

GestionEvenementASP/Views/Event/CreateEventg.cshtml
@using DAL.Interfaces;
@using DAL.Models;
@model IEnumerable<DAL.Models.EventTypeDay>
@inject IEventService eventService

@{
   ViewData["Title"] = "AddType";
}

<h1>AddType</h1>

<h4>Event</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="AddType">
         @{
            int i = 0;
            foreach (var et in Model)
            {
               <p>Jour@(i+1) @et.Date.ToString("D") :  </p>
               <div class="form-group">
                  <label asp-for="@et.Type" class="control-label"></label>
                  <select asp-for="@et.Type.Id" class="form-select" aria-label="Choisir Genre">
                     @foreach (var item in eventService.GetTypes())
                     {
                        <option value="@item.Id">@item.Name</option>
                     }
                  </select>
                  <span asp-validation-for="@et.Type.Id" class="text-danger"></span>
               </div>
               i++;
               <br />
            }
         }
         <div class="form-group">
            <input type="submit" value="Envoyer" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
   }

GestionEvenementASP/Views/Event/List.cshtml
@model IEnumerable<DAL.Models.Event>

@{
   ViewData["Title"] = "List";
}

<h1 class="text-center">Les Evenements : </h1>

<table class="table">
   <thead>
      <tr>
         <th>
            Evenement
         </th>
         <th>
            Commence le
         </th>
         <th>
            Termine le
         </th>
         <th>
            Pays
         </th>
         <th>
            Adresse
         </th>
         <th>
            Status
         </th>
      </tr>
   </thead>
   <tbody>
      @foreach (var item in Model)
      {
         <tr>

            <td>
               @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
               @item.StartDate.ToString("d")
            </td>
            <td>
               @item.EndDate.ToString("d")
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
               <span class="badge rounded-pill  text-bg-primary">@Html.DisplayFor(modelItem => item.Status)</span>
            </td>

         </tr>
         <tr>
            <th>Themes: </th>
            @{
               int i = 1;
               foreach (var et in item.TypeByDays)
               {
                  <td>Jour @i: <span>@et.Type.Name</span></td>
                  i++;
               }
            }
         </tr>
      }
   </tbody>
</table>

GestionEvenementASP/Views/Home/Index.cshtml
@using GestionEvenementASP.Tools;
@inject SessionManager session;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

   @if(session.ConnectedUser == null)
   {
      <h1 class="display-4">Welcome</h1>
   }
   else
   {
      <h1 class="display-4">Bienvenue sur Eventia, @session.ConnectedUser.LastName @session.ConnectedUser.FirstName </h1>
      <p>Cette application va vous aider à bien gérer vos Evenements </p>

      if (session.ConnectedUser.Role.Id == 4)
      {
         <a asp-action="Create" asp-controller="Event">Creer event</a>
      }
   }
</div>

GestionEvenementASP/Views/Shared/_Layout.cshtml
@using GestionEvenementASP.Tools;
@inject SessionManager session;
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - GestionEvenementASP</title>
   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
   <link rel="stylesheet" href="~/GestionEvenementASP.styles.css" asp-append-version="true" />
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">


</head>
<body>
   <header>
      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eventia</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
               <ul class="navbar-nav flex-grow-1">
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="List">Evenements</a>
                  </li>
               </ul>
               <ul class="navbar-nav">

                  @{
                     if (session.ConnectedUser is null)
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                     }
                     else
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Profil" asp-route-id="@session.ConnectedUser.Id">@session.ConnectedUser.LastName @session.ConnectedUser.FirstName</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                        </li>
                     }
                     if (session.ConnectedUser is not null && session.ConnectedUser.Role.Id == 4)
                     {
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List">Users</a>
                        </li>
                     }
                  }
               </ul>
            </div>
         </div>
      </nav>
   </header>
   <div class="container">
      <main role="main" class="pb-3">
         @RenderBody()
      </main>
   </div>

   <footer class="border-top footer text-muted">
      <div class="container">
         &copy; 2023 - GestionEvenementASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
   </footer>
   <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.fr.min.js"></script>
   <script src="~/js/site.js" asp-append-version="true"></script>
   @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestionEvenementASP/Views/User/Login.cshtml
@model GestionEvenementASP.Models.Forms.UserLoginForm

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<hr />
<p class="text-danger">@ViewBag.Error</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   <p>Pas encore de compte? ==> <a asp-action="Register">S'inscrire'</a></p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionEvenementASP/Views/User/Profil.cshtml
@using GestionEvenementASP.Tools;
@model DAL.Models.User
@inject SessionManager sessionManager

@{
   ViewData["Title"] = "Profil";
}

<h1>Profil</h1>

<h4>User</h4>
<hr />
<div class="row">
   <div class="col-md-4">
      <form asp-action="UpdateUser">
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         <div class="form-group visually-hidden">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control " type="hidden" />
            <span asp-validation-for="Id" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
         </div>
         <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
         </div>
         @{
            if(sessionManager.ConnectedUser.Role.Id > 1 )
            {
               <div class="form-group">
                  <label asp-for="GSM" class="control-label"></label>
                  <input asp-for="GSM" class="form-control" />
                  <span asp-validation-for="GSM" class="text-danger"></span>
               </div>
               <div class="form-group">
                  <label asp-for="NickName" class="control-label"></label>
                  <input asp-for="NickName" class="form-control" />
                  <span asp-validation-for="NickName" class="text-danger"></span>
               </div>
               <div class="form-group">
                  <label asp-for="Allergie" class="control-label"></label>
                  <input asp-for="Allergie" class="form-control" />
                  <span asp-validation-for="Allergie" class="text-danger"></span>
               </div>
               <div class="form-group">
                  <label asp-for="InfoSupp" class="control-label"></label>
                  <input asp-for="InfoSupp" class="form-control" />
                  <span asp-validation-for="InfoSupp" class="text-danger"></span>
               </div>
            }
         }
         <div class="form-group">
            <input type="submit" value="Sauver les changements" class="btn btn-primary" />
         </div>
      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

GestionEvenementASP/Views/User/Register.cshtml
@model GestionEvenementASP.Models.Forms.UserRegisterForm

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>UserRegisterForm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordConfirmation" class="control-label"></label>
                <input asp-for="PasswordConfirmation" class="form-control" />
                <span asp-validation-for="PasswordConfirmation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="S'inscrire'" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   <p>Vous avez déjà un compte ==> <a asp-action="Login">Se connecter</a></p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}